version: '3.1'
services:
    db:
        image: mysql:5.7
        container_name: mysql
        ports:
            - 33060:3306
        networks:
            - nodenet
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - /soft/mysql/mysql-node/conf:/etc/mysql
            - /soft/mysql/mysql-node/data:/var/lib/mysql
    mytest:
        build:
            context: ./
            dockerfile: Dockerfile
        image: mynode:v2.0.0
        container_name: mynodejs
        depends_on:
            - db
        ports: 
            - 3001:3000
networks:
    nodenet:
        driver: bridge
