apiVersion: apps/v1
kind: deployment
metadata:
  namespace: test
  name: pipeline
  labels:
    app: pipeline
spec: 
  replicas: 2
  selector:
    matchlabel: 
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers: 
        - name: pipeline
          image: 39.103.66.129:80/repo/pipeline:v4.0.0
          imagePullPolicy: Alyways
          ports: 
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata: 
  namespace: test
  labels:
    app: pipeline
  name: pipeline
spec:
  selector: 
      app: pipeline
  ports: 
  - port: 3001
    targetPort: 3000
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: test
  name: pipeline
spec:
  ingressClassName: ingress
  rules:
  - host: andrea.pipeline.com
    http:
    - paths: /
      pathType: Prefix 
      backend:
        service:
          name: pipeline
          port:
            number: 3001